version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    container_name: sec105_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root